// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_lofNZQqgKe_9sVXmcDZIZFXTnBnYAc',
    appId: '1:754568431988:web:d65458f37fb56311a48421',
    messagingSenderId: '754568431988',
    projectId: 'phr-app-ede00',
    authDomain: 'phr-app-ede00.firebaseapp.com',
    storageBucket: 'phr-app-ede00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBOFJLqXu8yQ4FpE4GVg-z9t1uqEDsFTA',
    appId: '1:754568431988:android:41ff5a069358b887a48421',
    messagingSenderId: '754568431988',
    projectId: 'phr-app-ede00',
    storageBucket: 'phr-app-ede00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFb9p8v4zLBBrt_An3VxihEC6ZL6m3CxY',
    appId: '1:754568431988:ios:286d05d4d40970e3a48421',
    messagingSenderId: '754568431988',
    projectId: 'phr-app-ede00',
    storageBucket: 'phr-app-ede00.appspot.com',
    iosClientId: '754568431988-mrda47ip2jbk7fc98lascn8hkk29l6lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.phr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFb9p8v4zLBBrt_An3VxihEC6ZL6m3CxY',
    appId: '1:754568431988:ios:286d05d4d40970e3a48421',
    messagingSenderId: '754568431988',
    projectId: 'phr-app-ede00',
    storageBucket: 'phr-app-ede00.appspot.com',
    iosClientId: '754568431988-mrda47ip2jbk7fc98lascn8hkk29l6lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.phr',
  );
}
